CREATE TABLE IF NOT EXISTS product
(
    id INT(11) NOT NULL,
    order_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id)
);