CREATE TABLE IF NOT EXISTS tb_order
(
    id BIGINT(20) NOT NULL,
    user_id BIGINT(20) NOT NULL,
    order_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES tb_user(id)
);